Repository cnumr/EcoIndex, pull requests merged in 2024-01, with the labels that each got.

#304 fix: multilingual redirect on URL testing from the result page
  assets/js/index.js
Labels: bug

#183 Feat/env variables
  assets/js/services/ApiService.js
  config/_default/params.toml
Labels: keep open

#313 feat: display the screenshot of the webpage that has been analyzed
  assets/js/components/SiteAnalysisResult.js
  assets/js/services/AnalysisService.js
  assets/js/services/ApiService.js
  layouts/partials/widgets/result-appreciation.html
Labels: enhancement, Front

#318 Fix: badge paragraph on the result page
  assets/js/components/SiteAnalysisResult.js
  assets/js/index.js
  content/en/result/_40_badge.md
  content/fr/result/_40_badge.md
  layouts/shortcodes/result-date.html
Labels: bug, javascript, Front
